# Generated by Django 4.0.6 on 2023-02-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt', '0002_image_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='Posted_Images'),
        ),
    ]
