# Generated by Django 4.0.6 on 2023-02-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt', '0003_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='Posted_Images')),
            ],
        ),
    ]
