# Generated by Django 4.0.6 on 2023-02-19 18:38

import appt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt', '0004_apis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=appt.models.upload_to),
        ),
    ]
