# Generated by Django 4.0.6 on 2023-02-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appt', '0005_alter_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIs',
        ),
    ]
